### ISSUE TITLE
Error while running data step with riboformer 6.1

### ISSUE THREAD

**Issue by NicolasProvencher** [jdcla/transcript_transformer#3]
Hi,
so Ive been trying your lastest iteration of riboformer and while running the data step i come up with this error

```bash
Processed assembly data restored (/home/noxatras/scratch/riboformer/reference/Homo_sapiens.GRCh38.109.chr.h5)
--> parsed transcriptome directory found, assembly information can not be re-processed (for existing h5 files).
Loading in GSE103719...
Traceback (most recent call last):
  File "/opt/conda/envs/ribo/bin/riboformer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/transcript_transformer/riboformer.py", line 60, in main
    f = process_data(args)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/transcript_transformer/data.py", line 80, in process_data
    parse_ribo_experiments(
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/transcript_transformer/data.py", line 109, in parse_ribo_experiments
    df = pl.read_csv(
         ^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/polars/utils/decorators.py", line 126, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/polars/utils/decorators.py", line 35, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/polars/io/csv.py", line 361, in read_csv
    df = DataFrame._read_csv(
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.12/site-packages/polars/internals/dataframe/frame.py", line 781, in _read_csv
    self._df = PyDataFrame.read_csv(
               ^^^^^^^^^^^^^^^^^^^^^
exceptions.ComputeError: projection index 3 is out of bounds for CSV schema with 3 columns
```

Since there is no csv implicated in the overall workflow i am kinda at a loss about whats cuasing the error

if there is extra information you need dont hesitate to ask

Thank a lot

**Comment by jdcla** [comment]
You stracktrace does not line up with the code lines of the newest transcript_transformer package. Are you certain you updated the tool correctly?

**Comment by NicolasProvencher** [comment]
aaaaaaa thank you, it installed the version 6.1

**Comment by NicolasProvencher** [comment]
By default biobear v 0.13.7 isnt avalaible in pip anymore is there a fix for that, can later version of biobear still work with the transcript_transformer package?

**Comment by NicolasProvencher** [comment]
There is a way to get the right version of biobear using conda libraries
`conda install biobear==0.13.7`

Though i am not sure that forcing the use of conda was the goal since you made your tool avalaible through pip

If 0.13.7 is the only possible version of biobear i suggest you specify how to get it in in the read.me as a step before installing pytorch

hopefully this helps

**Comment by jdcla** [comment]
Thanks for pointing this out. I have updated dependencies so pip install now properly installs the latest transcript-transformer version.
